version: '3.8'
services:
  devcontainer:
    build:
      context: ./..
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "tail -F /dev/null"
    volumes:
      - ..:/workspace:cached